# permissions for end users to view hosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: host-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kraut
    app.kubernetes.io/part-of: kraut
    app.kubernetes.io/managed-by: kustomize
  name: host-viewer-role
rules:
- apiGroups:
  - management.kraut.nicklasfrahm.dev
  resources:
  - hosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.kraut.nicklasfrahm.dev
  resources:
  - hosts/status
  verbs:
  - get
