apiVersion: management.kraut.nicklasfrahm.dev/v1alpha1
kind: Host
metadata:
  labels:
    app.kubernetes.io/instance: november
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kraut
  name: november
spec:
  # (required) The protocol to use for the connection.
  protocol: SSH
  # (required) The network address of the appliance.
  host: 172.16.0.241
  # Configure options specific to the SSH protocol.
  ssh:
    # (optional) Configure the host key fingerprint to prevent PitM attacks.
    fingerprint: SHA256:F2RZFjxyQuDQqdnv8nIC85oJru6//C9bQGwqgDE1n4w
    # (optional) Specify a user. Defaults to root.
    user: nicklasfrahm
  # (required) Configure the credentials.
  secretRef:
    # (required) The name of the secret that contains the credentials.
    name: kraut-host-ssh
