name: OIDC test

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write

jobs:
  test-oidc:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: ACTIONS_ID_TOKEN_REQUEST_URL
        run: echo $ACTIONS_ID_TOKEN_REQUEST_URL
