# (required) Configure settings that apply to all resources.
global:
  # (required) The fully qualified domain name of the cluster.
  fqdn: "aar1.nicklasfrahm.dev"

# (optional) An OIDC proxy to allow workload identity federation via RFC8693.
oidcproxy:
  # (optional) Disable the OIDC proxy if you use a different
  # solution, such as Entra ID workload identity federation.
  enabled: false

# (optional) An Envoy Gateway to allow traffic into the cluster.
envoygateway:
  # (optional) Disable the Envoy Gateway if you use a different
  # solution, such as an Ingress Controller.
  enabled: true

# (optional) A cert-manager to provision trusted certificates via Let's Encrypt.
certmanager:
  # (optional) Disable cert-manager if you would like to manage you own
  # installation.
  enabled: false

# (optional) Configure the operator.
operator:
  # (optional) Disabling the operator is currently only supported for testing purposes.
  enabled: false
